export const EMAIL_ERROR_VALIDATION = 'Please type valid email'
export const EMAIL_REQUIRED_VALIDATION = 'You must specify a email'
export const PASSWORD_REQUIRED_VALIDATION = 'You must specify a password'
export const PASSWORD_ERROR_VALIDATION = 'Password must be longer than 8 characters'
export const REPEAT_PASSWORD_ERROR_VALIDATION = 'Passwords must be the same'
export const IS_REQUIRED_FIELD = 'This field is required'
